In [1]:
%matplotlib widget
import matplotlib.animation as animation
import numpy as np
import matplotlib.pyplot as plt

In [2]:
n=100
x=np.random.randn(n)


In [3]:
def update(curr,x):
    if curr==n:
        a.event_source.stop()
    plt.cla()
    bins=np.arange(-4,4,0.5)
    plt.hist(x[:curr],bins=bins)
    plt.axis([-4,4,0,30])

In [4]:
fig=plt.figure()
a=animation.FuncAnimation(fig,update,interval=1,fargs=(x,))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation

fig, ax = plt.subplots()
xdata, ydata = [], []
ln, = plt.plot([], [], 'ro')

def init():
    ax.set_xlim(0, 2*np.pi)
    ax.set_ylim(-1, 1)
    return ln,

def update(frame):
    xdata.append(frame)
    ydata.append(np.sin(frame))
    ln.set_data(xdata, ydata)
    return ln,

ani = FuncAnimation(fig, update, frames=np.linspace(0, 2*np.pi, 128),
                    init_func=init, blit=True)
plt.show()

In [1]:
import matplotlib.pyplot as plt
import numpy as np

%matplotlib widget

# generate 4 random variables from the random, gamma, exponential, and uniform distributions
x1 = np.random.normal(-2.5, 1, 10000)
x2 = np.random.gamma(2, 1.5, 10000)
x3 = np.random.exponential(2, 10000)+7
x4 = np.random.uniform(14,20, 10000)

# plot the histograms
plt.figure(figsize=(9,3))
plt.hist(x1, normed=True, bins=20, alpha=0.5)
plt.hist(x2, normed=True, bins=20, alpha=0.5)
plt.hist(x3, normed=True, bins=20, alpha=0.5)
plt.hist(x4, normed=True, bins=20, alpha=0.5);
plt.axis([-7,21,0,0.6])

plt.text(x1.mean()-1.5, 0.5, 'x1\nNormal')
plt.text(x2.mean()-1.5, 0.5, 'x2\nGamma')
plt.text(x3.mean()-1.5, 0.5, 'x3\nExponential')
plt.text(x4.mean()-1.5, 0.5, 'x4\nUniform')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

/Users/aushakanuz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:14: MatplotlibDeprecationWarning: 
The 'normed' kwarg was deprecated in Matplotlib 2.1 and will be removed in 3.1. Use 'density' instead.
  
/Users/aushakanuz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:15: MatplotlibDeprecationWarning: 
The 'normed' kwarg was deprecated in Matplotlib 2.1 and will be removed in 3.1. Use 'density' instead.
  from ipykernel import kernelapp as app
/Users/aushakanuz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:16: MatplotlibDeprecationWarning: 
The 'normed' kwarg was deprecated in Matplotlib 2.1 and will be removed in 3.1. Use 'density' instead.
  app.launch_new_instance()
/Users/aushakanuz/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:17: MatplotlibDeprecationWarning: 
The 'normed' kwarg was deprecated in Matplotlib 2.1 and will be removed in 3.1. Use 'density' instead.


Text(15.508537514310756, 0.5, 'x4\nUniform')

In [6]:
%matplotlib widget
from matplotlib.animation import FuncAnimation
import random
import numpy as np
from itertools import count
import pandas as pd
import matplotlib.pyplot as plt 

In [7]:
x=[]
y=[]
index=count()
fig=plt.figure()
def animate(i):
    plt.cla()
    x.append(next(index))
    y.append(random.randint(0,5))
    plt.plot(x,y)
    
ani=FuncAnimation(fig,animate,interval=100)

plt.tight_layout()
plt.show()


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [8]:
x=np.random.rand(100)
index=count()
fig=plt.figure()

def animate(i):
    plt.cla()
    plt.hist(x[:next(index)],bins=np.arange[-4,4,0.5])
    
ani=FuncAnimation(fig,animate,interval=100)

plt.tight_layout()
plt.show()


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [9]:
b=np.arange(-4,4,0.5)

In [10]:
plt.figure()
plt.hist(x,bins=b)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 47., 53.,  0.,  0.,  0.,
         0.,  0.]),
 array([-4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,
         1.5,  2. ,  2.5,  3. ,  3.5]),
 <a list of 15 Patch objects>)

In [6]:
next(a)

1

In [11]:
x=np.random.randn(100)
plt.hist(x[:30])

(array([1., 3., 2., 6., 4., 2., 5., 2., 3., 2.]),
 array([-2.27593989, -1.843313  , -1.4106861 , -0.9780592 , -0.5454323 ,
        -0.1128054 ,  0.3198215 ,  0.7524484 ,  1.1850753 ,  1.6177022 ,
         2.0503291 ]),
 <a list of 10 Patch objects>)

In [12]:
plt.figure()
plt.hist(x[:next(a)],bins=20)


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

TypeError: 'FuncAnimation' object is not an iterator

In [13]:
min(x)

-2.9161232197919986

In [1]:
%matplotlib widget
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

n = 100
number_of_frames = 10
data = np.random.randn(n)


fig = plt.figure()

# plt.axis([-4,4,0,30])

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [2]:
count=[]
def update_hist(num, data):
    if num==100:
        a.event_source.stop()
    plt.cla()
    plt.hist(data[:num],bins=np.arange(-4,4,0.5))
    plt.axis([-4,4,0,30])
    
    plt.annotate('n= {}'.format(num),[3,27])
    
a = animation.FuncAnimation(fig, update_hist, fargs=(data, ),interval=100)
plt.show()