In [ ]:
def yolo(hours,parts):
    
    part=hours/parts
    
    find(part,parts)
    

    

def find(part,parts,l=None):
    
    for i in range(2,part+1):
        
        if prime(i,part,parts):
            
    

def prime(i,part,parts,count=None):
    
    c=0
    if i==2:
        
        prime(i+part)
    for j in range(2,i):
        
        if i%j==0:
            c+=1
    
    if count==0:
        prime

In [1]:
def example(l,a):
    
    
    l.sort()
    for i in range(a):
        
        maximumNum=l[-1]
        newNum=maximumNum//2
        l[-1]=newNum
        l.sort()
    
    return sum(l)

example([20,5,7,4],3)

17

In [ ]:
class stocks:
    
    def __init__(self,_id,trade,name,price,quantity):
        
        self.id=_id
        self.trade=trade
        self.name=name
        self.price=int(price)
        self.quantity=int(quantity)

        

def stocks():
    
    n=int(input())
    sell={}
    buy={}
    
    for i in range(n):
        
        text=input().split()
        
        stock=stocks(text[0],text[1],text[2],text[3],text[4])
        
        if stock.trade=="Sell":
            
            sell[stock.name]={
                "id":stock.id,
                "price":stock.price,
                "quantity":stock.quantity
            }
            
            continue 
        
        
            
        
        
    

In [4]:
import numpy as np
import sklearn
from sklearn.preprocessing import Binarizer
a=np.array([[7.1,-2.3,0.3],[-4.2,6.8,-5.1],[-3.2,9.8,2.1]])

binarizer_1 = Binarizer(1.1)
binarizer_1.fit_transform(a)
  

/Users/aushakanuz/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:68: FutureWarning: Pass threshold=1.1 as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 1.]])

In [5]:
def area(w,l,h):
    
    return 2*((w*l)+(l*h)+(h*w))


    

In [51]:
import numpy as np
from sklearn.linear_model import LinearRegression

x=np.array([-1,1,2,3]).reshape((-1, 1))
y=np.array([1,3,4,5])
model = LinearRegression().fit(x, y)

In [52]:
a=model.intercept_

In [54]:
b=model.coef_

In [55]:
a*a + b*b

array([3.46938776])

In [56]:
a*b

array([1.57142857])

In [57]:
a

array([1.57142857])

In [58]:
b

array([1.])

In [40]:
x

array([[-1],
       [ 1],
       [ 2],
       [ 3]])

In [59]:
import numpy as np
from sklearn.linear_model import LinearRegression

x=np.array([-1,1,2,3]).reshape((-1, 1))
y=np.array([1,3,4,5])
model = LinearRegression().fit(x, y)

In [60]:
x

array([[-1],
       [ 1],
       [ 2],
       [ 3]])

In [61]:
y

array([1, 3, 4, 5])

In [62]:
model.intercept_

2.0

In [63]:
model.coef_

array([1.])