In [1]:
import numpy as np 

In [3]:
a=[[[1,2,3],[3,4,5,6]],[[1,2,2],[1,1,1]]]

In [4]:
a=np.array(a)

In [5]:
a

array([[list([1, 2, 3]), list([3, 4, 5, 6])],
       [list([1, 2, 2]), list([1, 1, 1])]], dtype=object)

In [6]:
np.arange(3,14,2)

array([ 3,  5,  7,  9, 11, 13])

In [8]:
np.ones((32,33),dtype="int32")

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]], dtype=int32)

In [11]:
np.random.randint(10,100,(3,3))

array([[50, 37, 82],
       [34, 82, 23],
       [67, 72, 43]])

In [13]:
np.random.rand(4,5)

array([[0.01059755, 0.08587484, 0.9396816 , 0.44260776, 0.93228972],
       [0.21182062, 0.63662832, 0.85299198, 0.33906996, 0.10782065],
       [0.82013468, 0.7227763 , 0.54471721, 0.81380866, 0.39820761],
       [0.47386288, 0.11352308, 0.0083856 , 0.38715337, 0.3240773 ]])