In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib widget

In [2]:
n=np.random.normal(loc=0,scale=1,size=10000)
r=np.random.random(size=10000)
g=np.random.gamma(2,size=10000)

In [3]:
n

array([-0.89916604,  0.27196321,  2.05914411, ..., -0.72830277,
        1.74824182,  0.39179428])

In [4]:
r

array([0.29696425, 0.7032841 , 0.33175332, ..., 0.20703373, 0.26067727,
       0.47205663])

In [5]:
g

array([2.21159886, 1.50023042, 0.46387644, ..., 2.61841781, 0.35210405,
       1.3448156 ])

In [6]:
df=pd.DataFrame({
    "normal":n,
    "random":r,
    "gamme":g
})

In [7]:
df

normal    random     gamme
0    -0.899166  0.296964  2.211599
1     0.271963  0.703284  1.500230
2     2.059144  0.331753  0.463876
3    -1.675046  0.765826  0.881896
4     1.027371  0.029532  1.786649
...        ...       ...       ...
9995 -0.084309  0.570109  0.610173
9996  0.436822  0.176118  0.456025
9997 -0.728303  0.207034  2.618418
9998  1.748242  0.260677  0.352104
9999  0.391794  0.472057  1.344816

[10000 rows x 3 columns]

In [8]:
df.describe()

normal        random         gamme
count  10000.000000  10000.000000  10000.000000
mean       0.001198      0.497851      1.994219
std        1.009962      0.288571      1.405021
min       -3.754528      0.000005      0.016657
25%       -0.661156      0.252197      0.959532
50%       -0.005805      0.497475      1.678364
75%        0.672851      0.743675      2.691224
max        4.068645      0.999870     13.031950

In [9]:
plt.figure()
_=plt.boxplot(df["normal"],whis="range")

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [10]:
plt.clf()

In [11]:
_=plt.boxplot([df["normal"],df["random"],df["gamme"]],whis="range")

In [12]:
plt.figure()
_=plt.hist(df["gamme"],bins=100)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [13]:
import mpl_toolkits.axes_grid1.inset_locator as mpl_il

In [14]:
plt.figure()
_=plt.boxplot([df["normal"],df["random"],df["gamme"]],whis="range")
ax2=mpl_il.inset_axes(plt.gca(),width="60%",height="40%",loc=2)
ax2.hist(df["gamme"],bins=100)
ax2.margins(x=0.5)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [15]:
ax2.yaxis.tick_right()